#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

# Java 8 Update 40 or higher (8u40+), 64-bit is required
if [ "x$JAVA8_HOME" == "x" ] ; then
  JAVA_MAJOR_VER=$(java -version 2>&1 | grep "version" | awk '{print $3}' | tr -d \" | awk '{print substr($1,0,3)}')

  if [ $JAVA_MAJOR_VER != "1.8" ] ; then
    echo "Java 8 Update 40 or higher (8u40+), 64-bit is required."
    exit 1
  fi
else
  export JAVA_HOME=$JAVA8_HOME
  export PATH=$JAVA_HOME/bin:$PATH
fi

mvn clean install -DskipTests

mkdir -p build/presto-${PRESTO_VERSION}
mkdir -p build/presto-${PRESTO_VERSION}/docs

# Server
tar -C build/presto-${PRESTO_VERSION} --strip-components=1 -xzf presto-server/target/presto-server-${PRESTO_VERSION}.tar.gz
# CLI
cp -ra presto-cli/target/presto-cli-${PRESTO_VERSION}-executable.jar build/presto-${PRESTO_VERSION}/bin/presto
# Docs
cp -ra presto-docs/target/html/* build/presto-${PRESTO_VERSION}/docs/
# JDBC
cp -ra presto-jdbc/target/presto-jdbc-${PRESTO_VERSION}.jar build/presto-${PRESTO_VERSION}/lib/
# Verifier
cp -ra presto-verifier/target/presto-verifier-${PRESTO_VERSION}-executable.jar build/presto-${PRESTO_VERSION}/bin/verifier
# Benchmark Driver
cp -ra presto-benchmark-driver/target/presto-benchmark-driver-${PRESTO_VERSION}-executable.jar build/presto-${PRESTO_VERSION}/bin/presto-benchmark-driver
